#!/sdcard/bin/php
pkg update && pkg upgrade
pkg install nano
pkg install php
pkg install git 
pkg install toilet
pkg install figlet
pkg install ruby
pkg install lolcat
pkg install ncurses-utils
apt update
apt upgrade
apt install root-repo -y
apt install x11-repo -y
apt install termux-api
apt install mc -y
apt install php
apt install imagemagick
apt install tesseract
termux-setup-storage
